There is a chance for distutils, even in the win32all build process! This encourages me to further work on this script.
The specialized code for pywintypes and pythoncom should be clearer
now, at least to me.  Unfortunately, I broke mingw32 support.

But even before this, I get compilation errors with mingw. An example:
  win32/src/PyACL.cpp: In function `BOOL _ReorderACL(_ACL*)':
  win32/src/PyACL.cpp:89: `ACCESS_DENIED_OBJECT_ACE_TYPE' undeclared (first use
     this function)
  win32/src/PyACL.cpp:89: (Each undeclared identifier is reported only once for
     each function it appears in.)
  error: command 'gcc' failed with exit status 1

If someone tells me how this can be fixed I'll happy to also bring
this up to date for mingw.

swig is now supported (.i sources are parsed out of the dsp files),
and I can at least build
  pywintypes, win32api, win32file, win32event, pythoncom.

Whether they work or not - I cannot currently tell.

install_lib does no longer work, requires rethought:
Some files should be installed in the normal way, others go into sysdir.